apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-load-balancer-controller
rules:
- apiGroups: ["", "extensions", "networking.k8s.io", "coordination.k8s.io"]
  resources: ["ingresses", "ingresses/status", "ingressclasses", "services", "endpoints", "nodes", "pods", "configmaps", "events", "secrets", "namespaces", "leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["elbv2.k8s.aws"]
  resources: ["targetgroupbindings", "ingressclassparams"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
